name = "cargame_ada"
description = "Shiny new project"
version = "0.0.0"

authors = ["Esther O'Keefe"]
maintainers = ["Esther O'Keefe <esthermations@gmail.com>"]
maintainers-logins = ["esthermations"]

executables = ["cargame"]
project-files = ["cargame.gpr"]

[[depends-on]]  # This line was added by `alr with`
openglada = "~0.9.0"  # This line was added by `alr with`
openglada_glfw = "~0.9.0"  # This line was added by `alr with`
[[depends-on]]
gnatcoll = "^22.0.0"
